### ISSUE TITLE
Error when editing or creating a post

### ISSUE THREAD

**Issue by jerefrer** [danurbanowicz/eleventy-sveltia-cms-starter#4]
Hi there,

Thanks a lot for making it so simple to wire together all these great tools :)

I clicked the button to deploy to Netlify, followed the instructions on the README to configure Netlify and Github, and soon enough could access the admin page and everything seems to work well. I can create and edit pages, authors, and update the settings.
So far so good.

However when I click on a post to edit it, or try to create a new one, I get this error:

```console
Uncaught (in promise)
TypeError: o.map is not a function
    at ng (sveltia-cms.js:278:2593)
    at OK.t.$$.update (sveltia-cms.js:663:207488)
    at te (sveltia-cms.js:1:8888)
    at new PK (sveltia-cms.js:663:207573)
    at Gt (sveltia-cms.js:1:4333)
    at Array.Hx (sveltia-cms.js:663:245779)
    at ZS (sveltia-cms.js:663:233984)
    at Yx (sveltia-cms.js:663:250002)
    at te (sveltia-cms.js:1:8935)
    at new xg (sveltia-cms.js:663:253488)
```

I tried to do this locally, thinking that the error would be more helpful, but it is exactly the same.

Any idea what might be wrong?

**Comment by danurbanowicz** [comment]
I'm unable to look at this right now but it seems like it could be an issue with the tags list widget in the posts collection. You could try disabling that widget in your CMS config file and see if the error persists. Either way I will be able to take a look in a day or two.

**Comment by danurbanowicz** [comment]
This should now be fixed in https://github.com/danurbanowicz/eleventy-sveltia-cms-starter/pull/5

The post authors relation widget `search_fields` option is [no longer supported](https://github.com/sveltia/sveltia-cms/issues/17#issuecomment-1556302598) by Sveltia CMS and was causing the error.

Closing this now but let me know if the issue persists and I will re-open.

**Comment by jerefrer** [comment]
Hey that was fast :)

I confirm that the issue is fixed, thanks a lot! 🎉 🙏
